<?php

$schilderijen = [
	'meta' => [
		'count' => 42,
		'dimensions_unit' => 'cm',
		'dimensions_order' => 'hoogte_x_breedte',
		'size_categories' => [
			'K' => 'klein',
			'M' => 'middenmaat',
			'G' => 'groot',
		],
		'notes' => [
			'Nummer is het inventarisnummer en correspondeert met de naam van het fotobestand.',
			'Indien geen jaartal is vermeld, dan heeft Jan Roede het werk niet gedateerd.',
			'Werk is niet gesigneerd als dit niet expliciet staat vermeld.',
		],
	],
	'items' => [
		[
			'inventory_number' => 'JRD103',
			'image_name' => 'JRD103',
			'title' => 'Verborgen rechthoek',
			'format_code' => 'M',
			'format_label' => 'middenmaat',
			'height_cm' => 91,
			'width_cm' => 72,
			'year' => '1991',
			'signed' => true,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD104',
			'image_name' => 'JRD104',
			'title' => 'Speelse verering',
			'format_code' => 'M',
			'format_label' => 'middenmaat',
			'height_cm' => 91,
			'width_cm' => 72,
			'year' => null,
			'signed' => false,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD106',
			'image_name' => 'JRD106',
			'title' => 'Luchtsprong',
			'format_code' => 'M',
			'format_label' => 'middenmaat',
			'height_cm' => 91,
			'width_cm' => 72,
			'year' => null,
			'signed' => false,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD116',
			'image_name' => 'JRD116',
			'title' => 'Bijeenkomst',
			'format_code' => 'M',
			'format_label' => 'middenmaat',
			'height_cm' => 100,
			'width_cm' => 81,
			'year' => '1992',
			'signed' => true,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD119',
			'image_name' => 'JRD119',
			'title' => 'Maria II',
			'format_code' => 'M',
			'format_label' => 'middenmaat',
			'height_cm' => 100,
			'width_cm' => 81,
			'year' => null,
			'signed' => false,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD121',
			'image_name' => 'JRD121',
			'title' => 'Autoportrait',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 54,
			'width_cm' => 45,
			'year' => '1980',
			'signed' => true,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD126',
			'image_name' => 'JRD126',
			'title' => 'Monoloog',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 46,
			'width_cm' => 38,
			'year' => null,
			'signed' => false,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD132',
			'image_name' => 'JRD132',
			'title' => 'Ontevreden',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 55,
			'width_cm' => 46,
			'year' => null,
			'signed' => true,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD137',
			'image_name' => 'JRD137',
			'title' => 'Portret van een kunsthandelaar',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 56,
			'width_cm' => 47,
			'year' => null,
			'signed' => false,
			'material' => 'krijt/olieverf, linnen',
		],
		[
			'inventory_number' => 'JRD143',
			'image_name' => 'JRD143',
			'title' => 'Dans om de zon',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 63,
			'width_cm' => 46,
			'year' => '1973',
			'signed' => true,
			'material' => 'collage, papier',
		],
		[
			'inventory_number' => 'JRD144',
			'image_name' => 'JRD144',
			'title' => 'Van binnen naar buiten II',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 60,
			'width_cm' => 45,
			'year' => null,
			'signed' => false,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD151',
			'image_name' => 'JRD151',
			'title' => 'Nu',
			'format_code' => 'G',
			'format_label' => 'groot',
			'height_cm' => 114,
			'width_cm' => 146,
			'year' => '1978',
			'signed' => true,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD152',
			'image_name' => 'JRD152',
			'title' => 'Overdracht',
			'format_code' => 'G',
			'format_label' => 'groot',
			'height_cm' => 114,
			'width_cm' => 146,
			'year' => '1979',
			'signed' => true,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD159',
			'image_name' => 'JRD159',
			'title' => 'zonder titel',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 46,
			'width_cm' => 61,
			'year' => '1993',
			'signed' => true,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD160',
			'image_name' => 'JRD160',
			'title' => 'zonder titel',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 46,
			'width_cm' => 61,
			'year' => '1976',
			'signed' => true,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD163',
			'image_name' => 'JRD163',
			'title' => 'zonder titel',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 46,
			'width_cm' => 61,
			'year' => '1967',
			'signed' => true,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD179',
			'image_name' => 'JRD179',
			'title' => 'Voor het raam',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 45,
			'width_cm' => 53,
			'year' => '1964',
			'signed' => true,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD181',
			'image_name' => 'JRD181',
			'title' => 'De geliefden',
			'format_code' => 'M',
			'format_label' => 'middenmaat',
			'height_cm' => 90,
			'width_cm' => 72,
			'year' => '1976/78',
			'signed' => true,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD188',
			'image_name' => 'JRD188',
			'title' => 'Marjolijn',
			'format_code' => 'M',
			'format_label' => 'middenmaat',
			'height_cm' => 80,
			'width_cm' => 80,
			'year' => null,
			'signed' => false,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD197',
			'image_name' => 'JRD197',
			'title' => 'Zelfportret',
			'format_code' => 'M',
			'format_label' => 'middenmaat',
			'height_cm' => 91,
			'width_cm' => 72,
			'year' => '1985',
			'signed' => true,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD203',
			'image_name' => 'JRD203',
			'title' => 'Zelfportret ‘78',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 54,
			'width_cm' => 45,
			'year' => '1978',
			'signed' => true,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD205',
			'image_name' => 'JRD205',
			'title' => 'Portret van Marjolijn',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 61,
			'width_cm' => 46,
			'year' => null,
			'signed' => true,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD210',
			'image_name' => 'JRD210',
			'title' => 'Leo van Witsen',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 61,
			'width_cm' => 45,
			'year' => '1970',
			'signed' => true,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD220',
			'image_name' => 'JRD220',
			'title' => 'zonder titel',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 64,
			'width_cm' => 47,
			'year' => null,
			'signed' => true,
			'material' => 'olie, marouflé',
		],
		[
			'inventory_number' => 'JRD225',
			'image_name' => 'JRD225',
			'title' => 'Baudelaire',
			'format_code' => 'G',
			'format_label' => 'groot',
			'height_cm' => 100,
			'width_cm' => 81,
			'year' => null,
			'signed' => true,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD226',
			'image_name' => 'JRD226',
			'title' => 'Abstractie',
			'format_code' => 'G',
			'format_label' => 'groot',
			'height_cm' => 100,
			'width_cm' => 81,
			'year' => '1992',
			'signed' => true,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD232',
			'image_name' => 'JRD232',
			'title' => 'Le moindre de ses soucis',
			'format_code' => 'G',
			'format_label' => 'groot',
			'height_cm' => 114,
			'width_cm' => 146,
			'year' => '1969',
			'signed' => true,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD233',
			'image_name' => 'JRD233',
			'title' => 'Abstracte figuren in rook',
			'format_code' => 'G',
			'format_label' => 'groot',
			'height_cm' => 114,
			'width_cm' => 146,
			'year' => null,
			'signed' => false,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD235',
			'image_name' => 'JRD235',
			'title' => 'De brief',
			'format_code' => 'G',
			'format_label' => 'groot',
			'height_cm' => 114,
			'width_cm' => 146,
			'year' => '1979',
			'signed' => true,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD236',
			'image_name' => 'JRD236',
			'title' => 'Phantome discutant la vérité',
			'format_code' => 'G',
			'format_label' => 'groot',
			'height_cm' => 114,
			'width_cm' => 146,
			'year' => '1980',
			'signed' => true,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD242',
			'image_name' => 'JRD242',
			'title' => 'Androgyn',
			'format_code' => 'G',
			'format_label' => 'groot',
			'height_cm' => 114,
			'width_cm' => 146,
			'year' => '1987',
			'signed' => true,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD243',
			'image_name' => 'JRD243',
			'title' => 'Voortaan',
			'format_code' => 'G',
			'format_label' => 'groot',
			'height_cm' => 114,
			'width_cm' => 146,
			'year' => '1980',
			'signed' => true,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD246',
			'image_name' => 'JRD246',
			'title' => 'Liefdespaar',
			'format_code' => 'G',
			'format_label' => 'groot',
			'height_cm' => 146,
			'width_cm' => 114,
			'year' => '1988',
			'signed' => true,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD249',
			'image_name' => 'JRD249',
			'title' => 'Zelfportret',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 50,
			'width_cm' => 70,
			'year' => '1992',
			'signed' => true,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD252',
			'image_name' => 'JRD252',
			'title' => 'Lanzarote III',
			'format_code' => 'G',
			'format_label' => 'groot',
			'height_cm' => 180,
			'width_cm' => 150,
			'year' => '1989',
			'signed' => true,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD253',
			'image_name' => 'JRD253',
			'title' => 'Zonder van Dale',
			'format_code' => 'G',
			'format_label' => 'groot',
			'height_cm' => 145,
			'width_cm' => 180,
			'year' => '1990',
			'signed' => true,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD259',
			'image_name' => 'JRD259',
			'title' => 'Witte symbolen',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 46,
			'width_cm' => 55,
			'year' => '1983',
			'signed' => true,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD260',
			'image_name' => 'JRD260',
			'title' => 'zonder titel',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 46,
			'width_cm' => 61,
			'year' => '1999',
			'signed' => true,
			'material' => 'acryl, linnen',
		],
		[
			'inventory_number' => 'JRD261',
			'image_name' => 'JRD261',
			'title' => 'Figuur aan tafel',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 46,
			'width_cm' => 54,
			'year' => null,
			'signed' => true,
			'material' => 'acryl, marouflé',
		],
		[
			'inventory_number' => 'JRD269',
			'image_name' => 'JRD269',
			'title' => 'Marie',
			'format_code' => 'G',
			'format_label' => 'groot',
			'height_cm' => 146,
			'width_cm' => 114,
			'year' => '1990',
			'signed' => true,
			'material' => 'olie, linnen',
		],
		[
			'inventory_number' => 'JRD271',
			'image_name' => 'JRD271',
			'title' => 'Figuren aan rode tafel',
			'format_code' => 'K',
			'format_label' => 'klein',
			'height_cm' => 46,
			'width_cm' => 54,
			'year' => null,
			'signed' => true,
			'material' => 'olie, marouflé',
		],
		[
			'inventory_number' => 'JRS002',
			'image_name' => 'JRS002',
			'title' => null,
			'format_code' => 'G',
			'format_label' => 'groot',
			'height_cm' => 114,
			'width_cm' => 146,
			'year' => '1983',
			'signed' => true,
			'material' => 'olie, linnen',
		],
	],
];
