<?php

$werkenOpPapier = [
	'meta' => [
		'count' => 39,
		'dimensions_unit' => 'cm',
		'dimensions_order' => 'hoogte_x_breedte',
		'notes' => [
			'Nummer is het inventarisnummer en correspondeert met de naam van het fotobestand.',
			'JR-nummers zijn ingelijste werken op papier.',
			'PP-nummers zijn werken op papier in passe-partout.',
			'TG-nummers zijn losse/niet-ingelijste werken op papier.',
			'Indien geen jaartal is vermeld, dan heeft Jan Roede het werk niet gedateerd.',
		],
	],
	'items' => [
		// ── Niet ingelijst ────────────────────────────────────────────────────
		// ── Ingelijst (JR) ────────────────────────────────────────────────────
		// Inactieve items, voorlopig buiten de catalogus gelaten:
		// [
		// 	'inventory_number' => 'JR108',
		// 	'image_name'       => 'JR108',
		// 	'title'            => 'zonder titel',
		// 	'material'         => 'potlood, papier',
		// 	'framing'          => 'ingelijst',
		// 	'height_cm'        => 13,
		// 	'width_cm'         => 16.5,
		// 	'year'             => '1973',
		// 	'signed'           => false,
		// 	'sale_price_eur'   => 300,
		// ],
		// [
		// 	'inventory_number' => 'JR109',
		// 	'image_name'       => 'JR109',
		// 	'title'            => 'zonder titel',
		// 	'material'         => 'potlood, papier',
		// 	'framing'          => 'ingelijst',
		// 	'height_cm'        => 13,
		// 	'width_cm'         => 16.5,
		// 	'year'             => '1973',
		// 	'signed'           => false,
		// 	'sale_price_eur'   => 300,
		// ],
		// [
		// 	'inventory_number' => 'JR110',
		// 	'image_name'       => 'JR110',
		// 	'title'            => 'zonder titel',
		// 	'material'         => 'potlood, papier',
		// 	'framing'          => 'ingelijst',
		// 	'height_cm'        => 13,
		// 	'width_cm'         => 16.5,
		// 	'year'             => '1973',
		// 	'signed'           => false,
		// 	'sale_price_eur'   => 300,
		// ],
		// [
		// 	'inventory_number' => 'JR127',
		// 	'image_name'       => 'JR127',
		// 	'title'            => 'zonder titel',
		// 	'material'         => 'potlood, papier',
		// 	'framing'          => 'ingelijst',
		// 	'height_cm'        => 13,
		// 	'width_cm'         => 16.5,
		// 	'year'             => '1973',
		// 	'signed'           => false,
		// 	'sale_price_eur'   => 300,
		// ],
		// [
		// 	'inventory_number' => 'JR146',
		// 	'image_name'       => 'JR146',
		// 	'title'            => 'zonder titel',
		// 	'material'         => 'gouache, papier',
		// 	'framing'          => 'ingelijst',
		// 	'height_cm'        => 10,
		// 	'width_cm'         => 12.5,
		// 	'year'             => '1992',
		// 	'signed'           => false,
		// 	'sale_price_eur'   => 300,
		// ],
		// [
		// 	'inventory_number' => 'PP07',
		// 	'image_name'       => 'PP07',
		// 	'title'            => 'zonder titel',
		// 	'material'         => 'inkt, papier',
		// 	'framing'          => 'passe-partout',
		// 	'height_cm'        => 11,
		// 	'width_cm'         => 13,
		// 	'year'             => '1985',
		// 	'signed'           => false,
		// 	'sale_price_eur'   => 200,
		// ],
		// [
		// 	'inventory_number' => 'PP14',
		// 	'image_name'       => 'PP14',
		// 	'title'            => 'zonder titel',
		// 	'material'         => 'inkt, waterverf, papier',
		// 	'framing'          => 'passe-partout',
		// 	'height_cm'        => 3,
		// 	'width_cm'         => 4,
		// 	'year'             => null,
		// 	'signed'           => false,
		// 	'sale_price_eur'   => 75,
		// ],
		// [
		// 	'inventory_number' => 'PP15',
		// 	'image_name'       => 'PP15',
		// 	'title'            => 'zonder titel',
		// 	'material'         => 'inkt, waterverf, papier',
		// 	'framing'          => 'passe-partout',
		// 	'height_cm'        => 3,
		// 	'width_cm'         => 4,
		// 	'year'             => null,
		// 	'signed'           => false,
		// 	'sale_price_eur'   => 75,
		// ],
		// [
		// 	'inventory_number' => 'PP17',
		// 	'image_name'       => 'PP17',
		// 	'title'            => 'zonder titel',
		// 	'material'         => 'inkt, waterverf, papier',
		// 	'framing'          => 'passe-partout',
		// 	'height_cm'        => 3,
		// 	'width_cm'         => 4,
		// 	'year'             => null,
		// 	'signed'           => false,
		// 	'sale_price_eur'   => 75,
		// ],
		// [
		// 	'inventory_number' => 'PP18',
		// 	'image_name'       => 'PP18',
		// 	'title'            => 'zonder titel',
		// 	'material'         => 'inkt, waterverf, papier',
		// 	'framing'          => 'passe-partout',
		// 	'height_cm'        => 3,
		// 	'width_cm'         => 4,
		// 	'year'             => null,
		// 	'signed'           => false,
		// 	'sale_price_eur'   => 75,
		// ],
		// [
		// 	'inventory_number' => 'PP20',
		// 	'image_name'       => 'PP20',
		// 	'title'            => 'zonder titel',
		// 	'material'         => 'inkt, waterverf, papier',
		// 	'framing'          => 'passe-partout',
		// 	'height_cm'        => 3,
		// 	'width_cm'         => 4,
		// 	'year'             => null,
		// 	'signed'           => false,
		// 	'sale_price_eur'   => 75,
		// ],
		// [
		// 	'inventory_number' => 'PP21',
		// 	'image_name'       => 'PP21',
		// 	'title'            => 'zonder titel',
		// 	'material'         => 'inkt, waterverf, papier',
		// 	'framing'          => 'passe-partout',
		// 	'height_cm'        => 3,
		// 	'width_cm'         => 4,
		// 	'year'             => null,
		// 	'signed'           => false,
		// 	'sale_price_eur'   => 75,
		// ],
		// [
		// 	'inventory_number' => 'PP22',
		// 	'image_name'       => 'PP22',
		// 	'title'            => 'zonder titel',
		// 	'material'         => 'potlood, waterverf, papier',
		// 	'framing'          => 'passe-partout',
		// 	'height_cm'        => 5.5,
		// 	'width_cm'         => 7,
		// 	'year'             => null,
		// 	'signed'           => false,
		// 	'sale_price_eur'   => 95,
		// ],
		// [
		// 	'inventory_number' => 'PP24',
		// 	'image_name'       => 'PP24',
		// 	'title'            => 'zonder titel',
		// 	'material'         => 'potlood, waterverf, papier',
		// 	'framing'          => 'passe-partout',
		// 	'height_cm'        => 6,
		// 	'width_cm'         => 7,
		// 	'year'             => null,
		// 	'signed'           => false,
		// 	'sale_price_eur'   => 95,
		// ],
		[
			'inventory_number' => 'JR111',
			'image_name'       => 'JR111',
			'title'            => 'zonder titel',
			'material'         => 'zwart papier, witte inkt, collage',
			'framing'          => 'ingelijst',
			'height_cm'        => 12.5,
			'width_cm'         => 10,
			'year'             => null,
			'signed'           => false,
			'sale_price_eur'   => 250,
		],
		[
			'inventory_number' => 'JR115',
			'image_name'       => 'JR115',
			'title'            => 'zonder titel',
			'material'         => 'inkt, papier',
			'framing'          => 'ingelijst',
			'height_cm'        => 16,
			'width_cm'         => 19,
			'year'             => null,
			'signed'           => false,
			'sale_price_eur'   => 450,
		],
		[
			'inventory_number' => 'JR124',
			'image_name'       => 'JR124',
			'title'            => 'zonder titel',
			'material'         => 'viltstift, papier',
			'framing'          => 'ingelijst',
			'height_cm'        => 16,
			'width_cm'         => 13,
			'year'             => '1980',
			'signed'           => false,
			'sale_price_eur'   => 300,
		],
		[
			'inventory_number' => 'JR125',
			'image_name'       => 'JR125',
			'title'            => 'zonder titel',
			'material'         => 'inkt, papier',
			'framing'          => 'ingelijst',
			'height_cm'        => 14,
			'width_cm'         => 12,
			'year'             => null,
			'signed'           => false,
			'sale_price_eur'   => 300,
		],
		[
			'inventory_number' => 'JR126',
			'image_name'       => 'JR126',
			'title'            => 'zonder titel',
			'material'         => 'inkt, papier',
			'framing'          => 'ingelijst',
			'height_cm'        => 14,
			'width_cm'         => 12,
			'year'             => null,
			'signed'           => false,
			'sale_price_eur'   => 300,
		],

		[
			'inventory_number' => 'JR133',
			'image_name'       => 'JR133',
			'title'            => 'zonder titel',
			'material'         => 'inkt, papier',
			'framing'          => 'ingelijst',
			'height_cm'        => 16,
			'width_cm'         => 13,
			'year'             => '1980',
			'signed'           => false,
			'sale_price_eur'   => 350,
		],

		[
			'inventory_number' => 'JR148',
			'image_name'       => 'JR148',
			'title'            => 'zonder titel',
			'material'         => 'potlood, waterverf, papier',
			'framing'          => 'ingelijst',
			'height_cm'        => 31,
			'width_cm'         => 24,
			'year'             => '1989',
			'signed'           => false,
			'sale_price_eur'   => 550,
		],
		[
			'inventory_number' => 'JR151',
			'image_name'       => 'JR151',
			'title'            => 'zonder titel',
			'material'         => 'inkt, papier',
			'framing'          => 'ingelijst',
			'height_cm'        => 17,
			'width_cm'         => 13,
			'year'             => null,
			'signed'           => false,
			'sale_price_eur'   => 300,
		],
		[
			'inventory_number' => 'JR152',
			'image_name'       => 'JR152',
			'title'            => 'zonder titel',
			'material'         => 'potlood, inkt, papier',
			'framing'          => 'ingelijst',
			'height_cm'        => 14,
			'width_cm'         => 18,
			'year'             => '1989',
			'signed'           => false,
			'sale_price_eur'   => 350,
		],
		[
			'inventory_number' => 'JR170',
			'image_name'       => 'JR170',
			'title'            => 'zonder titel',
			'material'         => 'inkt, gekleurd papier',
			'framing'          => 'ingelijst',
			'height_cm'        => 21,
			'width_cm'         => 32,
			'year'             => '1964',
			'signed'           => false,
			'sale_price_eur'   => 550,
		],
		[
			'inventory_number' => 'JR171',
			'image_name'       => 'JR171',
			'title'            => 'zonder titel',
			'material'         => 'potlood, viltstift, papier',
			'framing'          => 'ingelijst',
			'height_cm'        => 27,
			'width_cm'         => 35.5,
			'year'             => '1983',
			'signed'           => false,
			'sale_price_eur'   => 600,
		],
		[
			'inventory_number' => 'JR189',
			'image_name'       => 'JR189',
			'title'            => '5 pentekeningen',
			'material'         => 'inkt, papier',
			'framing'          => 'ingelijst',
			'height_cm'        => 15,
			'width_cm'         => 11,
			'year'             => '1954',
			'signed'           => false,
			'edition_note'     => '5 stuks per set',
			'sale_price_eur'   => 900,
		],
		// ── Passe-partout (PP) ────────────────────────────────────────────────
		[
			'inventory_number' => 'PP01',
			'image_name'       => 'PP01',
			'title'            => 'zonder titel',
			'material'         => 'inkt, papier',
			'framing'          => 'passe-partout',
			'height_cm'        => 9,
			'width_cm'         => 11,
			'year'             => null,
			'signed'           => false,
			'sale_price_eur'   => 200,
		],
		[
			'inventory_number' => 'PP02',
			'image_name'       => 'PP02',
			'title'            => 'zonder titel',
			'material'         => 'viltstift, papier, collage',
			'framing'          => 'passe-partout',
			'height_cm'        => 10,
			'width_cm'         => 10,
			'year'             => null,
			'signed'           => false,
			'sale_price_eur'   => 100,
		],
		[
			'inventory_number' => 'PP03',
			'image_name'       => 'PP03',
			'title'            => 'zonder titel',
			'material'         => 'inkt, papier',
			'framing'          => 'passe-partout',
			'height_cm'        => 10,
			'width_cm'         => 11.5,
			'year'             => null,
			'signed'           => false,
			'sale_price_eur'   => 180,
		],
		[
			'inventory_number' => 'PP05',
			'image_name'       => 'PP05',
			'title'            => 'zonder titel',
			'material'         => 'inkt, papier',
			'framing'          => 'passe-partout',
			'height_cm'        => 10,
			'width_cm'         => 11.5,
			'year'             => null,
			'signed'           => false,
			'sale_price_eur'   => 200,
		],
		[
			'inventory_number' => 'PP06',
			'image_name'       => 'PP06',
			'title'            => 'zonder titel',
			'material'         => 'inkt, papier',
			'framing'          => 'passe-partout',
			'height_cm'        => 10.5,
			'width_cm'         => 12,
			'year'             => '1985',
			'signed'           => false,
			'sale_price_eur'   => 200,
		],

		[
			'inventory_number' => 'PP08',
			'image_name'       => 'PP08',
			'title'            => 'zonder titel',
			'material'         => 'potlood, waterverf, papier',
			'framing'          => 'passe-partout',
			'height_cm'        => 7.5,
			'width_cm'         => 14,
			'year'             => '1971',
			'signed'           => false,
			'sale_price_eur'   => 160,
		],
		[
			'inventory_number' => 'PP09',
			'image_name'       => 'PP09',
			'title'            => 'zonder titel',
			'material'         => 'viltstift, papier',
			'framing'          => 'passe-partout',
			'height_cm'        => 12,
			'width_cm'         => 16,
			'year'             => null,
			'signed'           => false,
			'sale_price_eur'   => 200,
		],
		[
			'inventory_number' => 'PP11',
			'image_name'       => 'PP11',
			'title'            => 'zonder titel',
			'material'         => 'viltstift, papier',
			'framing'          => 'passe-partout',
			'height_cm'        => 10,
			'width_cm'         => 14.5,
			'year'             => null,
			'signed'           => false,
			'sale_price_eur'   => 200,
		],
		[
			'inventory_number' => 'PP12',
			'image_name'       => 'PP12',
			'title'            => 'zonder titel',
			'material'         => 'inkt, papier',
			'framing'          => 'passe-partout',
			'height_cm'        => 31.5,
			'width_cm'         => 20,
			'year'             => '1964',
			'signed'           => false,
			'sale_price_eur'   => 350,
		],
		[
			'inventory_number' => 'PP16',
			'image_name'       => 'PP16',
			'title'            => 'zonder titel',
			'material'         => 'waterverf, papier',
			'framing'          => 'passe-partout',
			'height_cm'        => 6,
			'width_cm'         => 5.5,
			'year'             => null,
			'signed'           => false,
			'sale_price_eur'   => 110,
		],
		[
			'inventory_number' => 'PP25',
			'image_name'       => 'PP25',
			'title'            => 'zonder titel',
			'material'         => 'potlood, waterverf, papier',
			'framing'          => 'passe-partout',
			'height_cm'        => 8,
			'width_cm'         => 7,
			'year'             => null,
			'signed'           => false,
			'sale_price_eur'   => 95,
		],
	],
];
